version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}.0"

before_build:
  - nuget restore
  - ps: .\Build\Replace-FileString -Pattern '\$version\$' -Replacement "$env:appveyor_build_version" -Path .\Source\LuceneQueryParser.nuspec -Overwrite

configuration: Release

build:
  project: Exceptionless.LuceneQueryParser.sln
  publish_nuget: true
  publish_nuget_symbols: true
  
deploy:
  - provider: Environment
    name: NuGet

notifications:
  - provider: Slack
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX
    channel: notifications
