pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    VERSION_PREFIX=$(sed -n 's/.*<VersionPrefix>\([^<]*\)<\/VersionPrefix>.*/\1/p' <<< cat ./build/common.props)
    if [ "$(git tag --points-at)" == "" ]; then
      VERSION_SUFFIX="$BUILD_BUILDID-pre"
      VERSION="$VERSION_PREFIX.$VERSION_SUFFIX"
      echo "Version: $VERSION"
    else
      VERSION_SUFFIX=$BUILD_BUILDID
      VERSION="$VERSION_PREFIX.$VERSION_SUFFIX"
      echo "Version: $VERSION Tag: $(git tag --points-at)
    fi
    docker build --target testrunner -t foundatio:test --build-arg VERSION_SUFFIX=${VERSION_SUFFIX} .
    docker run -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    docker run --net=host -v $(Build.ArtifactStagingDirectory):/app/artifacts foundatio:test
    docker build --target pack -t foundatio:pack --build-arg VERSION_SUFFIX=${VERSION_SUFFIX} .
    docker run -v $(Build.ArtifactStagingDirectory):/app/artifacts foundatio:pack

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
