services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.5
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - foundatio
    healthcheck:
      interval: 2s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.19.5
    ports:
      - 5601:5601
    networks:
      - foundatio
    healthcheck:
      interval: 2s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - "1433:1433" # login with sa:P@ssword1
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=P@ssword1"
      - "MSSQL_PID=Developer"
    user: root
    networks:
      - foundatio
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-Usa",
          "-PP@ssword1",
          "-Q",
          "select 1",
        ]
      interval: 1s
      retries: 20

  ready:
    image: andrewlock/wait-for-dependencies
    command: elasticsearch:9200
    depends_on:
      - elasticsearch
      - sqlserver
    networks:
      - foundatio

networks:
  foundatio:
    driver: bridge
    name: foundatio
