services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - foundatio

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.15.1
    ports:
      - 5601:5601
    networks:
      - foundatio

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:1.0.7
    ports:
      - "1433:1433" # login with sa:P@ssword1
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=P@ssword1"
      - "MSSQL_PID=Developer"
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-Usa",
          "-PP@ssword1",
          "-Q",
          "select 1",
        ]
      interval: 1s
      retries: 20

  ready:
    image: andrewlock/wait-for-dependencies
    command: elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - foundatio

networks:
  foundatio:
    driver: bridge
    name: foundatio
