// -----------------------------------------------------------------------
// <auto-generated>
//   This code was generated by Pegasus 3.1.2.0
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------

namespace
#line 1 "lucene-query.peg"
            Exceptionless.LuceneQueryParser
#line default
{
    using System;
    using System.Collections.Generic;
    using Pegasus.Common;
    using
        #line 3 "lucene-query.peg"
       System.Linq
        #line default
        ;
    using
        #line 4 "lucene-query.peg"
       Exceptionless.LuceneQueryParser.Nodes
        #line default
        ;

    /// <summary>
    ///  Parses a string according to the rules of the <see cref="QueryParser" /> grammar.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Pegasus", "3.1.2.0")]
    public
    partial class
    #line 2 "lucene-query.peg"
           QueryParser
    #line default
    {
        #line 7 "lucene-query.peg"
 
    public class FieldInfo {
        public string Field { get; set; }
        public string Prefix { get; set; }
    }
        #line default

        /// <summary>
        ///  Parses a string according to the rules of the <see cref="QueryParser" /> grammar.
        /// </summary>
        /// <param name="subject">The parsing subject.</param>
        /// <param name="fileName">The optional file name to use in error messages.</param>
        /// <returns>The <see cref="GroupNode" /> parsed from <paramref name="subject" />.</returns>
        /// <exception cref="FormatException">
        ///  Thrown when parsing fails against <paramref name="subject"/>.  The exception's <code>Data["cursor"]</code> will be set with the cursor where the fatal error occurred.
        /// </exception>
        public GroupNode Parse(string subject, string fileName = null)
        {
            IList<LexicalElement> lexicalElements;
            return this.Parse(subject, fileName, out lexicalElements);
        }

        /// <summary>
        ///  Parses a string according to the rules of the <see cref="QueryParser" /> grammar.
        /// </summary>
        /// <param name="subject">The parsing subject.</param>
        /// <param name="fileName">The optional file name to use in error messages.</param>
        /// <param name="lexicalElements">When this method returns, contains the lexical elements for the parsing subject. This parameter is passed uninitialized.</param>
        /// <returns>The <see cref="GroupNode" /> parsed from <paramref name="subject" />.</returns>
        /// <exception cref="FormatException">
        ///  Thrown when parsing fails against <paramref name="subject"/>.  The exception's <code>Data["cursor"]</code> will be set with the cursor where the fatal error occurred.
        /// </exception>
        public GroupNode Parse(string subject, string fileName, out IList<LexicalElement> lexicalElements)
        {
            var cursor = new Cursor(subject, 0, fileName);
            var result = this.start(ref cursor);
            if (result == null)
            {
                throw ExceptionHelper(cursor, state => "Failed to parse 'start'.");
            }
            var lexical = (cursor["_lexical"] as ListNode<LexicalElement>).ToList();
            lexical.Reverse();
            lexicalElements = lexical.AsReadOnly();
            return result.Value;
        }

        private IParseResult<
            #line 14 "lucene-query.peg"
      GroupNode
            #line default
            > start(ref Cursor cursor)
        {
            IParseResult<GroupNode> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<IList<IList<string>>> r1 = null;
                var startCursor1 = cursor;
                var l0 = new List<IList<string>>();
                while (true)
                {
                    IParseResult<IList<string>> r2 = null;
                    r2 = this._(ref cursor);
                    if (r2 != null)
                    {
                        l0.Add(r2.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                r1 = this.ReturnHelper<IList<IList<string>>>(startCursor1, ref cursor, state => l0.AsReadOnly());
                if (r1 != null)
                {
                    IParseResult<GroupNode> r3 = null;
                    var nodeStart = cursor;
                    r3 = this.node(ref cursor);
                    var nodeEnd = cursor;
                    var node = ValueOrDefault(r3);
                    if (r3 != null)
                    {
                        r0 = this.ReturnHelper<GroupNode>(startCursor0, ref cursor, state =>
                            #line 16 "lucene-query.peg"
     
        node
                            #line default
                            );
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor2 = cursor;
                IParseResult<IList<IList<string>>> r4 = null;
                var startCursor3 = cursor;
                var l1 = new List<IList<string>>();
                while (true)
                {
                    IParseResult<IList<string>> r5 = null;
                    r5 = this._(ref cursor);
                    if (r5 != null)
                    {
                        l1.Add(r5.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                r4 = this.ReturnHelper<IList<IList<string>>>(startCursor3, ref cursor, state => l1.AsReadOnly());
                if (r4 != null)
                {
                    IParseResult<string> r6 = null;
                    r6 = this.EOF(ref cursor);
                    if (r6 != null)
                    {
                        r0 = this.ReturnHelper<GroupNode>(startCursor2, ref cursor, state =>
                            #line 20 "lucene-query.peg"
     
        new GroupNode()
                            #line default
                            );
                    }
                    else
                    {
                        cursor = startCursor2;
                    }
                }
                else
                {
                    cursor = startCursor2;
                }
            }
            if (r0 == null)
            {
                var startCursor4 = cursor;
                throw this.ExceptionHelper(startCursor4, state =>
                    #line 23 "lucene-query.peg"
            "Unable to parse query."
                    #line default
                    );
            }
            return r0;
        }

        private IParseResult<
            #line 25 "lucene-query.peg"
     GroupNode
            #line default
            > node(ref Cursor cursor)
        {
            IParseResult<GroupNode> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                var opStart = cursor;
                r1 = this.operator_exp(ref cursor);
                var opEnd = cursor;
                var op = ValueOrDefault(r1);
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.EOF(ref cursor);
                    if (r2 != null)
                    {
                        r0 = this.ReturnHelper<GroupNode>(startCursor0, ref cursor, state =>
                            #line 27 "lucene-query.peg"
     
        new GroupNode {
            Operator = op
        }
                            #line default
                            );
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor1 = cursor;
                IParseResult<string> r3 = null;
                var opStart = cursor;
                r3 = this.operator_exp(ref cursor);
                var opEnd = cursor;
                var op = ValueOrDefault(r3);
                if (r3 != null)
                {
                    IParseResult<GroupNode> r4 = null;
                    var rightStart = cursor;
                    r4 = this.node(ref cursor);
                    var rightEnd = cursor;
                    var right = ValueOrDefault(r4);
                    if (r4 != null)
                    {
                        r0 = this.ReturnHelper<GroupNode>(startCursor1, ref cursor, state =>
                            #line 33 "lucene-query.peg"
     
        right
                            #line default
                            );
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            if (r0 == null)
            {
                var startCursor2 = cursor;
                IParseResult<IQueryNode> r5 = null;
                var leftStart = cursor;
                r5 = this.group_exp(ref cursor);
                var leftEnd = cursor;
                var left = ValueOrDefault(r5);
                if (r5 != null)
                {
                    IParseResult<string> r6 = null;
                    var opStart = cursor;
                    var startCursor3 = cursor;
                    IParseResult<IList<string>> r7 = null;
                    var startCursor4 = cursor;
                    var l0 = new List<string>();
                    while (true)
                    {
                        IParseResult<string> r8 = null;
                        r8 = this.operator_exp(ref cursor);
                        if (r8 != null)
                        {
                            l0.Add(r8.Value);
                        }
                        else
                        {
                            break;
                        }
                    }
                    r7 = this.ReturnHelper<IList<string>>(startCursor4, ref cursor, state => l0.AsReadOnly());
                    if (r7 != null)
                    {
                        IParseResult<string> r9 = null;
                        r9 = this.ParseLiteral(ref cursor, "");
                        if (r9 != null)
                        {
                            {
                                var len = cursor.Location - startCursor3.Location;
                                r6 = this.ReturnHelper<string>(startCursor3, ref cursor, state =>
                                    state.Subject.Substring(startCursor3.Location, len)
                                    );
                            }
                        }
                        else
                        {
                            cursor = startCursor3;
                        }
                    }
                    else
                    {
                        cursor = startCursor3;
                    }
                    var opEnd = cursor;
                    var op = ValueOrDefault(r6);
                    if (r6 != null)
                    {
                        IParseResult<IList<GroupNode>> r10 = null;
                        var rightStart = cursor;
                        var startCursor5 = cursor;
                        var l1 = new List<GroupNode>();
                        while (true)
                        {
                            IParseResult<GroupNode> r11 = null;
                            r11 = this.node(ref cursor);
                            if (r11 != null)
                            {
                                l1.Add(r11.Value);
                            }
                            else
                            {
                                break;
                            }
                        }
                        r10 = this.ReturnHelper<IList<GroupNode>>(startCursor5, ref cursor, state => l1.AsReadOnly());
                        var rightEnd = cursor;
                        var right = ValueOrDefault(r10);
                        if (r10 != null)
                        {
                            r0 = this.ReturnHelper<GroupNode>(startCursor2, ref cursor, state =>
                                #line 37 "lucene-query.peg"
     {
        var node= new GroupNode {
            Left = left
        };

        var rightExp =
                right.Count == 0
                ? (TermNode)null
                : right[0].Right == null
                    ? right[0].Left
                    : right[0];

        if (rightExp != null)
        {
            node.Operator = !String.IsNullOrEmpty(op) ? op.Trim() : null;
            node.Right = rightExp;
        }

        return node;
    }
                                #line default
                                );
                        }
                        else
                        {
                            cursor = startCursor2;
                        }
                    }
                    else
                    {
                        cursor = startCursor2;
                    }
                }
                else
                {
                    cursor = startCursor2;
                }
            }
            return r0;
        }

        private IParseResult<
            #line 58 "lucene-query.peg"
          IQueryNode
            #line default
            > group_exp(ref Cursor cursor)
        {
            IParseResult<IQueryNode> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<IQueryNode> r1 = null;
                var field_expStart = cursor;
                r1 = this.field_exp(ref cursor);
                var field_expEnd = cursor;
                var field_exp = ValueOrDefault(r1);
                if (r1 != null)
                {
                    IParseResult<IList<IList<string>>> r2 = null;
                    var startCursor1 = cursor;
                    var l0 = new List<IList<string>>();
                    while (true)
                    {
                        IParseResult<IList<string>> r3 = null;
                        r3 = this._(ref cursor);
                        if (r3 != null)
                        {
                            l0.Add(r3.Value);
                        }
                        else
                        {
                            break;
                        }
                    }
                    r2 = this.ReturnHelper<IList<IList<string>>>(startCursor1, ref cursor, state => l0.AsReadOnly());
                    if (r2 != null)
                    {
                        r0 = this.ReturnHelper<IQueryNode>(startCursor0, ref cursor, state =>
                            #line 60 "lucene-query.peg"
     
        field_exp
                            #line default
                            );
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                r0 = this.paren_exp(ref cursor);
            }
            return r0;
        }

        private IParseResult<
            #line 65 "lucene-query.peg"
          GroupNode
            #line default
            > paren_exp(ref Cursor cursor)
        {
            IParseResult<GroupNode> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParseLiteral(ref cursor, "(");
            if (r1 != null)
            {
                IParseResult<GroupNode> r2 = null;
                var nodeStart = cursor;
                r2 = this.node(ref cursor);
                var nodeEnd = cursor;
                var node = ValueOrDefault(r2);
                if (r2 != null)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.ParseLiteral(ref cursor, ")");
                    if (r3 != null)
                    {
                        IParseResult<IList<double>> r4 = null;
                        var boostStart = cursor;
                        var startCursor1 = cursor;
                        var l0 = new List<double>();
                        while (l0.Count < 1)
                        {
                            IParseResult<double> r5 = null;
                            r5 = this.boost_modifier(ref cursor);
                            if (r5 != null)
                            {
                                l0.Add(r5.Value);
                            }
                            else
                            {
                                break;
                            }
                        }
                        r4 = this.ReturnHelper<IList<double>>(startCursor1, ref cursor, state => l0.AsReadOnly());
                        var boostEnd = cursor;
                        var boost = ValueOrDefault(r4);
                        if (r4 != null)
                        {
                            IParseResult<IList<IList<string>>> r6 = null;
                            var startCursor2 = cursor;
                            var l1 = new List<IList<string>>();
                            while (true)
                            {
                                IParseResult<IList<string>> r7 = null;
                                r7 = this._(ref cursor);
                                if (r7 != null)
                                {
                                    l1.Add(r7.Value);
                                }
                                else
                                {
                                    break;
                                }
                            }
                            r6 = this.ReturnHelper<IList<IList<string>>>(startCursor2, ref cursor, state => l1.AsReadOnly());
                            if (r6 != null)
                            {
                                r0 = this.ReturnHelper<GroupNode>(startCursor0, ref cursor, state =>
                                    #line 67 "lucene-query.peg"
     {
        node.HasParens = true;

        if (boost.Count > 0)
            node.Boost = boost.SingleOrDefault();

        return node;
    }
                                    #line default
                                    );
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 76 "lucene-query.peg"
          IQueryNode
            #line default
            > field_exp(ref Cursor cursor)
        {
            IParseResult<IQueryNode> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<IList<FieldInfo>> r1 = null;
                var nameStart = cursor;
                var startCursor1 = cursor;
                var l0 = new List<FieldInfo>();
                while (l0.Count < 1)
                {
                    IParseResult<FieldInfo> r2 = null;
                    r2 = this.fieldname(ref cursor);
                    if (r2 != null)
                    {
                        l0.Add(r2.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                r1 = this.ReturnHelper<IList<FieldInfo>>(startCursor1, ref cursor, state => l0.AsReadOnly());
                var nameEnd = cursor;
                var name = ValueOrDefault(r1);
                if (r1 != null)
                {
                    IParseResult<TermRangeNode> r3 = null;
                    var rangeStart = cursor;
                    r3 = this.range_operator_exp(ref cursor);
                    var rangeEnd = cursor;
                    var range = ValueOrDefault(r3);
                    if (r3 != null)
                    {
                        r0 = this.ReturnHelper<IQueryNode>(startCursor0, ref cursor, state =>
                            #line 78 "lucene-query.peg"
     {
        if (name.Count == 1) {
          range.Field = name[0].Field;
          range.Prefix = name[0].Prefix;
        }

        return range;
    }
                            #line default
                            );
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor2 = cursor;
                IParseResult<FieldInfo> r4 = null;
                var nameStart = cursor;
                r4 = this.fieldname(ref cursor);
                var nameEnd = cursor;
                var name = ValueOrDefault(r4);
                if (r4 != null)
                {
                    IParseResult<GroupNode> r5 = null;
                    var nodeStart = cursor;
                    r5 = this.paren_exp(ref cursor);
                    var nodeEnd = cursor;
                    var node = ValueOrDefault(r5);
                    if (r5 != null)
                    {
                        r0 = this.ReturnHelper<IQueryNode>(startCursor2, ref cursor, state =>
                            #line 87 "lucene-query.peg"
     {
        node.Field = name.Field;
        node.Prefix = name.Prefix;
        return node;
    }
                            #line default
                            );
                    }
                    else
                    {
                        cursor = startCursor2;
                    }
                }
                else
                {
                    cursor = startCursor2;
                }
            }
            if (r0 == null)
            {
                var startCursor3 = cursor;
                IParseResult<IList<FieldInfo>> r6 = null;
                var nameStart = cursor;
                var startCursor4 = cursor;
                var l1 = new List<FieldInfo>();
                while (l1.Count < 1)
                {
                    IParseResult<FieldInfo> r7 = null;
                    r7 = this.fieldname(ref cursor);
                    if (r7 != null)
                    {
                        l1.Add(r7.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                r6 = this.ReturnHelper<IList<FieldInfo>>(startCursor4, ref cursor, state => l1.AsReadOnly());
                var nameEnd = cursor;
                var name = ValueOrDefault(r6);
                if (r6 != null)
                {
                    IParseResult<TermNode> r8 = null;
                    var termStart = cursor;
                    r8 = this.term(ref cursor);
                    var termEnd = cursor;
                    var term = ValueOrDefault(r8);
                    if (r8 != null)
                    {
                        r0 = this.ReturnHelper<IQueryNode>(startCursor3, ref cursor, state =>
                            #line 93 "lucene-query.peg"
     {
        var query = new TermNode();

        if (name.Count == 1) {
          query.Field = name[0].Field;
          query.Prefix = name[0].Prefix;
        }

        term.CopyTo(query);

        return query;
    }
                            #line default
                            );
                    }
                    else
                    {
                        cursor = startCursor3;
                    }
                }
                else
                {
                    cursor = startCursor3;
                }
            }
            return r0;
        }

        private IParseResult<
            #line 106 "lucene-query.peg"
          FieldInfo
            #line default
            > fieldname(ref Cursor cursor)
        {
            IParseResult<FieldInfo> r0 = null;
            var startCursor0 = cursor;
            IParseResult<IList<string>> r1 = null;
            var opStart = cursor;
            var startCursor1 = cursor;
            var l0 = new List<string>();
            while (l0.Count < 1)
            {
                IParseResult<string> r2 = null;
                r2 = this.prefix_operator_exp(ref cursor);
                if (r2 != null)
                {
                    l0.Add(r2.Value);
                }
                else
                {
                    break;
                }
            }
            r1 = this.ReturnHelper<IList<string>>(startCursor1, ref cursor, state => l0.AsReadOnly());
            var opEnd = cursor;
            var op = ValueOrDefault(r1);
            if (r1 != null)
            {
                IParseResult<string> r3 = null;
                var fieldnameStart = cursor;
                r3 = this.name_term(ref cursor);
                var fieldnameEnd = cursor;
                var fieldname = ValueOrDefault(r3);
                if (r3 != null)
                {
                    IParseResult<IList<IList<string>>> r4 = null;
                    var startCursor2 = cursor;
                    var l1 = new List<IList<string>>();
                    while (true)
                    {
                        IParseResult<IList<string>> r5 = null;
                        r5 = this._(ref cursor);
                        if (r5 != null)
                        {
                            l1.Add(r5.Value);
                        }
                        else
                        {
                            break;
                        }
                    }
                    r4 = this.ReturnHelper<IList<IList<string>>>(startCursor2, ref cursor, state => l1.AsReadOnly());
                    if (r4 != null)
                    {
                        IParseResult<string> r6 = null;
                        r6 = this.ParseLiteral(ref cursor, ":");
                        if (r6 != null)
                        {
                            r0 = this.ReturnHelper<FieldInfo>(startCursor0, ref cursor, state =>
                                #line 108 "lucene-query.peg"
       {
        var result = new FieldInfo { Field = fieldname };

        result.Prefix = op.SingleOrDefault();

        return result;
    }
                                #line default
                                , ruleName: "fieldname");
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 116 "lucene-query.peg"
     TermNode
            #line default
            > term(ref Cursor cursor)
        {
            IParseResult<TermNode> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<IList<string>> r1 = null;
                var opStart = cursor;
                var startCursor1 = cursor;
                var l0 = new List<string>();
                while (l0.Count < 1)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.prefix_operator_exp(ref cursor);
                    if (r2 != null)
                    {
                        l0.Add(r2.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                r1 = this.ReturnHelper<IList<string>>(startCursor1, ref cursor, state => l0.AsReadOnly());
                var opEnd = cursor;
                var op = ValueOrDefault(r1);
                if (r1 != null)
                {
                    IParseResult<string> r3 = null;
                    var termStart = cursor;
                    r3 = this.quoted_term(ref cursor);
                    var termEnd = cursor;
                    var term = ValueOrDefault(r3);
                    if (r3 != null)
                    {
                        IParseResult<IList<double>> r4 = null;
                        var proximityStart = cursor;
                        var startCursor2 = cursor;
                        var l1 = new List<double>();
                        while (l1.Count < 1)
                        {
                            IParseResult<double> r5 = null;
                            r5 = this.proximity_modifier(ref cursor);
                            if (r5 != null)
                            {
                                l1.Add(r5.Value);
                            }
                            else
                            {
                                break;
                            }
                        }
                        r4 = this.ReturnHelper<IList<double>>(startCursor2, ref cursor, state => l1.AsReadOnly());
                        var proximityEnd = cursor;
                        var proximity = ValueOrDefault(r4);
                        if (r4 != null)
                        {
                            IParseResult<IList<double>> r6 = null;
                            var boostStart = cursor;
                            var startCursor3 = cursor;
                            var l2 = new List<double>();
                            while (l2.Count < 1)
                            {
                                IParseResult<double> r7 = null;
                                r7 = this.boost_modifier(ref cursor);
                                if (r7 != null)
                                {
                                    l2.Add(r7.Value);
                                }
                                else
                                {
                                    break;
                                }
                            }
                            r6 = this.ReturnHelper<IList<double>>(startCursor3, ref cursor, state => l2.AsReadOnly());
                            var boostEnd = cursor;
                            var boost = ValueOrDefault(r6);
                            if (r6 != null)
                            {
                                IParseResult<IList<IList<string>>> r8 = null;
                                var startCursor4 = cursor;
                                var l3 = new List<IList<string>>();
                                while (true)
                                {
                                    IParseResult<IList<string>> r9 = null;
                                    r9 = this._(ref cursor);
                                    if (r9 != null)
                                    {
                                        l3.Add(r9.Value);
                                    }
                                    else
                                    {
                                        break;
                                    }
                                }
                                r8 = this.ReturnHelper<IList<IList<string>>>(startCursor4, ref cursor, state => l3.AsReadOnly());
                                if (r8 != null)
                                {
                                    r0 = this.ReturnHelper<TermNode>(startCursor0, ref cursor, state =>
                                        #line 118 "lucene-query.peg"
       {
        var result = new TermNode { Term = term, IsQuotedTerm = true };

        if (proximity.Count > 0)
            result.Proximity = proximity.SingleOrDefault();

        if (boost.Count > 0)
            result.Boost = boost.SingleOrDefault();

        result.Prefix = op.SingleOrDefault();

        return result;
    }
                                        #line default
                                        );
                                }
                                else
                                {
                                    cursor = startCursor0;
                                }
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor5 = cursor;
                IParseResult<IList<string>> r10 = null;
                var opStart = cursor;
                var startCursor6 = cursor;
                var l4 = new List<string>();
                while (l4.Count < 1)
                {
                    IParseResult<string> r11 = null;
                    r11 = this.prefix_operator_exp(ref cursor);
                    if (r11 != null)
                    {
                        l4.Add(r11.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                r10 = this.ReturnHelper<IList<string>>(startCursor6, ref cursor, state => l4.AsReadOnly());
                var opEnd = cursor;
                var op = ValueOrDefault(r10);
                if (r10 != null)
                {
                    IParseResult<string> r12 = null;
                    var termStart = cursor;
                    r12 = this.unquoted_term(ref cursor);
                    var termEnd = cursor;
                    var term = ValueOrDefault(r12);
                    if (r12 != null)
                    {
                        IParseResult<IList<double>> r13 = null;
                        var proximityStart = cursor;
                        var startCursor7 = cursor;
                        var l5 = new List<double>();
                        while (l5.Count < 1)
                        {
                            IParseResult<double> r14 = null;
                            r14 = this.proximity_modifier(ref cursor);
                            if (r14 != null)
                            {
                                l5.Add(r14.Value);
                            }
                            else
                            {
                                break;
                            }
                        }
                        r13 = this.ReturnHelper<IList<double>>(startCursor7, ref cursor, state => l5.AsReadOnly());
                        var proximityEnd = cursor;
                        var proximity = ValueOrDefault(r13);
                        if (r13 != null)
                        {
                            IParseResult<IList<double>> r15 = null;
                            var boostStart = cursor;
                            var startCursor8 = cursor;
                            var l6 = new List<double>();
                            while (l6.Count < 1)
                            {
                                IParseResult<double> r16 = null;
                                r16 = this.boost_modifier(ref cursor);
                                if (r16 != null)
                                {
                                    l6.Add(r16.Value);
                                }
                                else
                                {
                                    break;
                                }
                            }
                            r15 = this.ReturnHelper<IList<double>>(startCursor8, ref cursor, state => l6.AsReadOnly());
                            var boostEnd = cursor;
                            var boost = ValueOrDefault(r15);
                            if (r15 != null)
                            {
                                IParseResult<IList<IList<string>>> r17 = null;
                                var startCursor9 = cursor;
                                var l7 = new List<IList<string>>();
                                while (true)
                                {
                                    IParseResult<IList<string>> r18 = null;
                                    r18 = this._(ref cursor);
                                    if (r18 != null)
                                    {
                                        l7.Add(r18.Value);
                                    }
                                    else
                                    {
                                        break;
                                    }
                                }
                                r17 = this.ReturnHelper<IList<IList<string>>>(startCursor9, ref cursor, state => l7.AsReadOnly());
                                if (r17 != null)
                                {
                                    r0 = this.ReturnHelper<TermNode>(startCursor5, ref cursor, state =>
                                        #line 132 "lucene-query.peg"
     {
        var result = new TermNode { Term = term };

        if (proximity.Count > 0)
            result.Proximity = proximity.SingleOrDefault();

        if (boost.Count > 0)
            result.Boost = boost.SingleOrDefault();

        result.Prefix = op.SingleOrDefault();

        return result;
    }
                                        #line default
                                        );
                                }
                                else
                                {
                                    cursor = startCursor5;
                                }
                            }
                            else
                            {
                                cursor = startCursor5;
                            }
                        }
                        else
                        {
                            cursor = startCursor5;
                        }
                    }
                    else
                    {
                        cursor = startCursor5;
                    }
                }
                else
                {
                    cursor = startCursor5;
                }
            }
            return r0;
        }

        private IParseResult<string> name_term(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            var termStart = cursor;
            var startCursor1 = cursor;
            IParseResult<IList<string>> r2 = null;
            var startCursor2 = cursor;
            var l0 = new List<string>();
            while (true)
            {
                IParseResult<string> r3 = null;
                r3 = this.ParseClass(ref cursor, "::  \t\t\r\r\n\n\f\f{{}}(())\"\"//^^~~[[]]", negated: true);
                if (r3 != null)
                {
                    l0.Add(r3.Value);
                }
                else
                {
                    break;
                }
            }
            if (l0.Count >= 1)
            {
                r2 = this.ReturnHelper<IList<string>>(startCursor2, ref cursor, state => l0.AsReadOnly());
            }
            else
            {
                cursor = startCursor2;
            }
            if (r2 != null)
            {
                IParseResult<string> r4 = null;
                r4 = this.ParseLiteral(ref cursor, "");
                if (r4 != null)
                {
                    {
                        var len = cursor.Location - startCursor1.Location;
                        r1 = this.ReturnHelper<string>(startCursor1, ref cursor, state =>
                            state.Subject.Substring(startCursor1.Location, len)
                            );
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            else
            {
                cursor = startCursor1;
            }
            var termEnd = cursor;
            var term = ValueOrDefault(r1);
            if (r1 != null)
            {
                r0 = this.ReturnHelper<string>(startCursor0, ref cursor, state =>
                    #line 148 "lucene-query.peg"
     
        term
                    #line default
                    );
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> unquoted_term(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            var termStart = cursor;
            var startCursor1 = cursor;
            IParseResult<IList<string>> r2 = null;
            var startCursor2 = cursor;
            var l0 = new List<string>();
            while (true)
            {
                IParseResult<string> r3 = null;
                r3 = this.ParseClass(ref cursor, "::  \t\t\r\r\n\n\f\f{{}}(())//^^~~[[]]", negated: true);
                if (r3 != null)
                {
                    l0.Add(r3.Value);
                }
                else
                {
                    break;
                }
            }
            if (l0.Count >= 1)
            {
                r2 = this.ReturnHelper<IList<string>>(startCursor2, ref cursor, state => l0.AsReadOnly());
            }
            else
            {
                cursor = startCursor2;
            }
            if (r2 != null)
            {
                IParseResult<string> r4 = null;
                r4 = this.ParseLiteral(ref cursor, "");
                if (r4 != null)
                {
                    {
                        var len = cursor.Location - startCursor1.Location;
                        r1 = this.ReturnHelper<string>(startCursor1, ref cursor, state =>
                            state.Subject.Substring(startCursor1.Location, len)
                            );
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            else
            {
                cursor = startCursor1;
            }
            var termEnd = cursor;
            var term = ValueOrDefault(r1);
            if (r1 != null)
            {
                r0 = this.ReturnHelper<string>(startCursor0, ref cursor, state =>
                    #line 154 "lucene-query.peg"
     
        term
                    #line default
                    );
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> range_unquoted_term(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            var termStart = cursor;
            var startCursor1 = cursor;
            IParseResult<IList<string>> r2 = null;
            var startCursor2 = cursor;
            var l0 = new List<string>();
            while (true)
            {
                IParseResult<string> r3 = null;
                r3 = this.ParseClass(ref cursor, "::  ..\t\t\r\r\n\n\f\f{{}}(())\"\"^^~~[[]]", negated: true);
                if (r3 != null)
                {
                    l0.Add(r3.Value);
                }
                else
                {
                    break;
                }
            }
            if (l0.Count >= 1)
            {
                r2 = this.ReturnHelper<IList<string>>(startCursor2, ref cursor, state => l0.AsReadOnly());
            }
            else
            {
                cursor = startCursor2;
            }
            if (r2 != null)
            {
                IParseResult<string> r4 = null;
                r4 = this.ParseLiteral(ref cursor, "");
                if (r4 != null)
                {
                    {
                        var len = cursor.Location - startCursor1.Location;
                        r1 = this.ReturnHelper<string>(startCursor1, ref cursor, state =>
                            state.Subject.Substring(startCursor1.Location, len)
                            );
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            else
            {
                cursor = startCursor1;
            }
            var termEnd = cursor;
            var term = ValueOrDefault(r1);
            if (r1 != null)
            {
                r0 = this.ReturnHelper<string>(startCursor0, ref cursor, state =>
                    #line 160 "lucene-query.peg"
     
        term
                    #line default
                    );
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> quoted_term(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParseLiteral(ref cursor, "\"");
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                var termStart = cursor;
                var startCursor1 = cursor;
                IParseResult<IList<string>> r3 = null;
                var startCursor2 = cursor;
                var l0 = new List<string>();
                while (true)
                {
                    IParseResult<string> r4 = null;
                    r4 = this.ParseClass(ref cursor, "\"\"", negated: true);
                    if (r4 != null)
                    {
                        l0.Add(r4.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                if (l0.Count >= 1)
                {
                    r3 = this.ReturnHelper<IList<string>>(startCursor2, ref cursor, state => l0.AsReadOnly());
                }
                else
                {
                    cursor = startCursor2;
                }
                if (r3 != null)
                {
                    IParseResult<string> r5 = null;
                    r5 = this.ParseLiteral(ref cursor, "");
                    if (r5 != null)
                    {
                        {
                            var len = cursor.Location - startCursor1.Location;
                            r2 = this.ReturnHelper<string>(startCursor1, ref cursor, state =>
                                state.Subject.Substring(startCursor1.Location, len)
                                );
                        }
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
                var termEnd = cursor;
                var term = ValueOrDefault(r2);
                if (r2 != null)
                {
                    IParseResult<string> r6 = null;
                    r6 = this.ParseLiteral(ref cursor, "\"");
                    if (r6 != null)
                    {
                        r0 = this.ReturnHelper<string>(startCursor0, ref cursor, state =>
                            #line 166 "lucene-query.peg"
     
        term
                            #line default
                            );
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 170 "lucene-query.peg"
               double
            #line default
            > boost_modifier(ref Cursor cursor)
        {
            IParseResult<double> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParseLiteral(ref cursor, "^");
            if (r1 != null)
            {
                IParseResult<double> r2 = null;
                var boostStart = cursor;
                r2 = this.decimal_or_int_exp(ref cursor);
                var boostEnd = cursor;
                var boost = ValueOrDefault(r2);
                if (r2 != null)
                {
                    r0 = this.ReturnHelper<double>(startCursor0, ref cursor, state =>
                        #line 172 "lucene-query.peg"
     
        boost
                        #line default
                        );
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 176 "lucene-query.peg"
                   double
            #line default
            > proximity_modifier(ref Cursor cursor)
        {
            IParseResult<double> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParseLiteral(ref cursor, "~");
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                var proximityStart = cursor;
                var startCursor1 = cursor;
                IParseResult<IList<double>> r3 = null;
                var startCursor2 = cursor;
                var l0 = new List<double>();
                while (l0.Count < 1)
                {
                    IParseResult<double> r4 = null;
                    r4 = this.decimal_or_int_exp(ref cursor);
                    if (r4 != null)
                    {
                        l0.Add(r4.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                r3 = this.ReturnHelper<IList<double>>(startCursor2, ref cursor, state => l0.AsReadOnly());
                if (r3 != null)
                {
                    IParseResult<string> r5 = null;
                    r5 = this.ParseLiteral(ref cursor, "");
                    if (r5 != null)
                    {
                        {
                            var len = cursor.Location - startCursor1.Location;
                            r2 = this.ReturnHelper<string>(startCursor1, ref cursor, state =>
                                state.Subject.Substring(startCursor1.Location, len)
                                );
                        }
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
                var proximityEnd = cursor;
                var proximity = ValueOrDefault(r2);
                if (r2 != null)
                {
                    r0 = this.ReturnHelper<double>(startCursor0, ref cursor, state =>
                        #line 178 "lucene-query.peg"
     
        String.IsNullOrEmpty(proximity) ? Double.MinValue : Double.Parse(proximity)
                        #line default
                        );
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 182 "lucene-query.peg"
                   double
            #line default
            > decimal_or_int_exp(ref Cursor cursor)
        {
            IParseResult<double> r0 = null;
            if (r0 == null)
            {
                r0 = this.decimal_exp(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.int_exp(ref cursor);
            }
            return r0;
        }

        private IParseResult<
            #line 186 "lucene-query.peg"
            double
            #line default
            > decimal_exp(ref Cursor cursor)
        {
            IParseResult<double> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParseLiteral(ref cursor, "0.");
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                var valStart = cursor;
                var startCursor1 = cursor;
                IParseResult<IList<string>> r3 = null;
                var startCursor2 = cursor;
                var l0 = new List<string>();
                while (true)
                {
                    IParseResult<string> r4 = null;
                    r4 = this.ParseClass(ref cursor, "09");
                    if (r4 != null)
                    {
                        l0.Add(r4.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                if (l0.Count >= 1)
                {
                    r3 = this.ReturnHelper<IList<string>>(startCursor2, ref cursor, state => l0.AsReadOnly());
                }
                else
                {
                    cursor = startCursor2;
                }
                if (r3 != null)
                {
                    IParseResult<string> r5 = null;
                    r5 = this.ParseLiteral(ref cursor, "");
                    if (r5 != null)
                    {
                        {
                            var len = cursor.Location - startCursor1.Location;
                            r2 = this.ReturnHelper<string>(startCursor1, ref cursor, state =>
                                state.Subject.Substring(startCursor1.Location, len)
                                );
                        }
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
                var valEnd = cursor;
                var val = ValueOrDefault(r2);
                if (r2 != null)
                {
                    r0 = this.ReturnHelper<double>(startCursor0, ref cursor, state =>
                        #line 188 "lucene-query.peg"
     
        Double.Parse("0." + val)
                        #line default
                        );
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 192 "lucene-query.peg"
        double
            #line default
            > int_exp(ref Cursor cursor)
        {
            IParseResult<double> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            var valStart = cursor;
            var startCursor1 = cursor;
            IParseResult<IList<string>> r2 = null;
            var startCursor2 = cursor;
            var l0 = new List<string>();
            while (true)
            {
                IParseResult<string> r3 = null;
                r3 = this.ParseClass(ref cursor, "09");
                if (r3 != null)
                {
                    l0.Add(r3.Value);
                }
                else
                {
                    break;
                }
            }
            if (l0.Count >= 1)
            {
                r2 = this.ReturnHelper<IList<string>>(startCursor2, ref cursor, state => l0.AsReadOnly());
            }
            else
            {
                cursor = startCursor2;
            }
            if (r2 != null)
            {
                IParseResult<string> r4 = null;
                r4 = this.ParseLiteral(ref cursor, "");
                if (r4 != null)
                {
                    {
                        var len = cursor.Location - startCursor1.Location;
                        r1 = this.ReturnHelper<string>(startCursor1, ref cursor, state =>
                            state.Subject.Substring(startCursor1.Location, len)
                            );
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            else
            {
                cursor = startCursor1;
            }
            var valEnd = cursor;
            var val = ValueOrDefault(r1);
            if (r1 != null)
            {
                r0 = this.ReturnHelper<double>(startCursor0, ref cursor, state =>
                    #line 194 "lucene-query.peg"
           
        Double.Parse(val)
                    #line default
                    );
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 198 "lucene-query.peg"
                   TermRangeNode
            #line default
            > range_operator_exp(ref Cursor cursor)
        {
            IParseResult<TermRangeNode> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.ParseLiteral(ref cursor, "[");
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    var term_minStart = cursor;
                    r2 = this.range_unquoted_term(ref cursor);
                    var term_minEnd = cursor;
                    var term_min = ValueOrDefault(r2);
                    if (r2 != null)
                    {
                        IParseResult<string> r3 = null;
                        var delimStart = cursor;
                        r3 = this.range_delimiter_exp(ref cursor);
                        var delimEnd = cursor;
                        var delim = ValueOrDefault(r3);
                        if (r3 != null)
                        {
                            IParseResult<string> r4 = null;
                            var term_maxStart = cursor;
                            r4 = this.range_unquoted_term(ref cursor);
                            var term_maxEnd = cursor;
                            var term_max = ValueOrDefault(r4);
                            if (r4 != null)
                            {
                                IParseResult<string> r5 = null;
                                r5 = this.ParseLiteral(ref cursor, "]");
                                if (r5 != null)
                                {
                                    r0 = this.ReturnHelper<TermRangeNode>(startCursor0, ref cursor, state =>
                                        #line 200 "lucene-query.peg"
     
        new TermRangeNode {
            Min = term_min,
            Max = term_max,
            MinInclusive = true,
            MaxInclusive = true,
            Delimiter = delim
        }
                                        #line default
                                        );
                                }
                                else
                                {
                                    cursor = startCursor0;
                                }
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor1 = cursor;
                IParseResult<string> r6 = null;
                r6 = this.ParseLiteral(ref cursor, "{");
                if (r6 != null)
                {
                    IParseResult<string> r7 = null;
                    var term_minStart = cursor;
                    r7 = this.range_unquoted_term(ref cursor);
                    var term_minEnd = cursor;
                    var term_min = ValueOrDefault(r7);
                    if (r7 != null)
                    {
                        IParseResult<string> r8 = null;
                        var delimStart = cursor;
                        r8 = this.range_delimiter_exp(ref cursor);
                        var delimEnd = cursor;
                        var delim = ValueOrDefault(r8);
                        if (r8 != null)
                        {
                            IParseResult<string> r9 = null;
                            var term_maxStart = cursor;
                            r9 = this.range_unquoted_term(ref cursor);
                            var term_maxEnd = cursor;
                            var term_max = ValueOrDefault(r9);
                            if (r9 != null)
                            {
                                IParseResult<string> r10 = null;
                                r10 = this.ParseLiteral(ref cursor, "}");
                                if (r10 != null)
                                {
                                    r0 = this.ReturnHelper<TermRangeNode>(startCursor1, ref cursor, state =>
                                        #line 210 "lucene-query.peg"
     
        new TermRangeNode {
            Min = term_min,
            Max = term_max,
            MinInclusive = false,
            MaxInclusive = false,
            Delimiter = delim
        }
                                        #line default
                                        );
                                }
                                else
                                {
                                    cursor = startCursor1;
                                }
                            }
                            else
                            {
                                cursor = startCursor1;
                            }
                        }
                        else
                        {
                            cursor = startCursor1;
                        }
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            if (r0 == null)
            {
                var startCursor2 = cursor;
                IParseResult<string> r11 = null;
                r11 = this.ParseLiteral(ref cursor, "{");
                if (r11 != null)
                {
                    IParseResult<string> r12 = null;
                    var term_minStart = cursor;
                    r12 = this.range_unquoted_term(ref cursor);
                    var term_minEnd = cursor;
                    var term_min = ValueOrDefault(r12);
                    if (r12 != null)
                    {
                        IParseResult<string> r13 = null;
                        var delimStart = cursor;
                        r13 = this.range_delimiter_exp(ref cursor);
                        var delimEnd = cursor;
                        var delim = ValueOrDefault(r13);
                        if (r13 != null)
                        {
                            IParseResult<string> r14 = null;
                            var term_maxStart = cursor;
                            r14 = this.range_unquoted_term(ref cursor);
                            var term_maxEnd = cursor;
                            var term_max = ValueOrDefault(r14);
                            if (r14 != null)
                            {
                                IParseResult<string> r15 = null;
                                r15 = this.ParseLiteral(ref cursor, "]");
                                if (r15 != null)
                                {
                                    r0 = this.ReturnHelper<TermRangeNode>(startCursor2, ref cursor, state =>
                                        #line 220 "lucene-query.peg"
     
        new TermRangeNode {
            Min = term_min,
            Max = term_max,
            MinInclusive = false,
            MaxInclusive = true,
            Delimiter = delim
        }
                                        #line default
                                        );
                                }
                                else
                                {
                                    cursor = startCursor2;
                                }
                            }
                            else
                            {
                                cursor = startCursor2;
                            }
                        }
                        else
                        {
                            cursor = startCursor2;
                        }
                    }
                    else
                    {
                        cursor = startCursor2;
                    }
                }
                else
                {
                    cursor = startCursor2;
                }
            }
            if (r0 == null)
            {
                var startCursor3 = cursor;
                IParseResult<string> r16 = null;
                r16 = this.ParseLiteral(ref cursor, "[");
                if (r16 != null)
                {
                    IParseResult<string> r17 = null;
                    var term_minStart = cursor;
                    r17 = this.range_unquoted_term(ref cursor);
                    var term_minEnd = cursor;
                    var term_min = ValueOrDefault(r17);
                    if (r17 != null)
                    {
                        IParseResult<string> r18 = null;
                        var delimStart = cursor;
                        r18 = this.range_delimiter_exp(ref cursor);
                        var delimEnd = cursor;
                        var delim = ValueOrDefault(r18);
                        if (r18 != null)
                        {
                            IParseResult<string> r19 = null;
                            var term_maxStart = cursor;
                            r19 = this.range_unquoted_term(ref cursor);
                            var term_maxEnd = cursor;
                            var term_max = ValueOrDefault(r19);
                            if (r19 != null)
                            {
                                IParseResult<string> r20 = null;
                                r20 = this.ParseLiteral(ref cursor, "}");
                                if (r20 != null)
                                {
                                    r0 = this.ReturnHelper<TermRangeNode>(startCursor3, ref cursor, state =>
                                        #line 230 "lucene-query.peg"
     
        new TermRangeNode {
            Min = term_min,
            Max = term_max,
            MinInclusive = true,
            MaxInclusive = false,
            Delimiter = delim
        }
                                        #line default
                                        );
                                }
                                else
                                {
                                    cursor = startCursor3;
                                }
                            }
                            else
                            {
                                cursor = startCursor3;
                            }
                        }
                        else
                        {
                            cursor = startCursor3;
                        }
                    }
                    else
                    {
                        cursor = startCursor3;
                    }
                }
                else
                {
                    cursor = startCursor3;
                }
            }
            return r0;
        }

        private IParseResult<string> range_delimiter_exp(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<IList<IList<string>>> r1 = null;
                var startCursor1 = cursor;
                var l0 = new List<IList<string>>();
                while (true)
                {
                    IParseResult<IList<string>> r2 = null;
                    r2 = this._(ref cursor);
                    if (r2 != null)
                    {
                        l0.Add(r2.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                if (l0.Count >= 1)
                {
                    r1 = this.ReturnHelper<IList<IList<string>>>(startCursor1, ref cursor, state => l0.AsReadOnly());
                }
                else
                {
                    cursor = startCursor1;
                }
                if (r1 != null)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.ParseLiteral(ref cursor, "TO");
                    if (r3 != null)
                    {
                        IParseResult<IList<IList<string>>> r4 = null;
                        var startCursor2 = cursor;
                        var l1 = new List<IList<string>>();
                        while (true)
                        {
                            IParseResult<IList<string>> r5 = null;
                            r5 = this._(ref cursor);
                            if (r5 != null)
                            {
                                l1.Add(r5.Value);
                            }
                            else
                            {
                                break;
                            }
                        }
                        if (l1.Count >= 1)
                        {
                            r4 = this.ReturnHelper<IList<IList<string>>>(startCursor2, ref cursor, state => l1.AsReadOnly());
                        }
                        else
                        {
                            cursor = startCursor2;
                        }
                        if (r4 != null)
                        {
                            {
                                var len = cursor.Location - startCursor0.Location;
                                r0 = this.ReturnHelper<string>(startCursor0, ref cursor, state =>
                                    state.Subject.Substring(startCursor0.Location, len)
                                    );
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor3 = cursor;
                IParseResult<IList<IList<string>>> r6 = null;
                var startCursor4 = cursor;
                var l2 = new List<IList<string>>();
                while (true)
                {
                    IParseResult<IList<string>> r7 = null;
                    r7 = this._(ref cursor);
                    if (r7 != null)
                    {
                        l2.Add(r7.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                r6 = this.ReturnHelper<IList<IList<string>>>(startCursor4, ref cursor, state => l2.AsReadOnly());
                if (r6 != null)
                {
                    IParseResult<string> r8 = null;
                    r8 = this.ParseLiteral(ref cursor, "..");
                    if (r8 != null)
                    {
                        IParseResult<IList<IList<string>>> r9 = null;
                        var startCursor5 = cursor;
                        var l3 = new List<IList<string>>();
                        while (true)
                        {
                            IParseResult<IList<string>> r10 = null;
                            r10 = this._(ref cursor);
                            if (r10 != null)
                            {
                                l3.Add(r10.Value);
                            }
                            else
                            {
                                break;
                            }
                        }
                        r9 = this.ReturnHelper<IList<IList<string>>>(startCursor5, ref cursor, state => l3.AsReadOnly());
                        if (r9 != null)
                        {
                            {
                                var len = cursor.Location - startCursor3.Location;
                                r0 = this.ReturnHelper<string>(startCursor3, ref cursor, state =>
                                    state.Subject.Substring(startCursor3.Location, len)
                                    );
                            }
                        }
                        else
                        {
                            cursor = startCursor3;
                        }
                    }
                    else
                    {
                        cursor = startCursor3;
                    }
                }
                else
                {
                    cursor = startCursor3;
                }
            }
            return r0;
        }

        private IParseResult<string> operator_exp(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<IList<IList<string>>> r1 = null;
                var startCursor1 = cursor;
                var l0 = new List<IList<string>>();
                while (true)
                {
                    IParseResult<IList<string>> r2 = null;
                    r2 = this._(ref cursor);
                    if (r2 != null)
                    {
                        l0.Add(r2.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                r1 = this.ReturnHelper<IList<IList<string>>>(startCursor1, ref cursor, state => l0.AsReadOnly());
                if (r1 != null)
                {
                    IParseResult<string> r3 = null;
                    var opStart = cursor;
                    r3 = this.@operator(ref cursor);
                    var opEnd = cursor;
                    var op = ValueOrDefault(r3);
                    if (r3 != null)
                    {
                        IParseResult<IList<IList<string>>> r4 = null;
                        var startCursor2 = cursor;
                        var l1 = new List<IList<string>>();
                        while (true)
                        {
                            IParseResult<IList<string>> r5 = null;
                            r5 = this._(ref cursor);
                            if (r5 != null)
                            {
                                l1.Add(r5.Value);
                            }
                            else
                            {
                                break;
                            }
                        }
                        if (l1.Count >= 1)
                        {
                            r4 = this.ReturnHelper<IList<IList<string>>>(startCursor2, ref cursor, state => l1.AsReadOnly());
                        }
                        else
                        {
                            cursor = startCursor2;
                        }
                        if (r4 != null)
                        {
                            r0 = this.ReturnHelper<string>(startCursor0, ref cursor, state =>
                                #line 246 "lucene-query.peg"
     
        op
                                #line default
                                );
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor3 = cursor;
                IParseResult<IList<IList<string>>> r6 = null;
                var startCursor4 = cursor;
                var l2 = new List<IList<string>>();
                while (true)
                {
                    IParseResult<IList<string>> r7 = null;
                    r7 = this._(ref cursor);
                    if (r7 != null)
                    {
                        l2.Add(r7.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                r6 = this.ReturnHelper<IList<IList<string>>>(startCursor4, ref cursor, state => l2.AsReadOnly());
                if (r6 != null)
                {
                    IParseResult<string> r8 = null;
                    var opStart = cursor;
                    r8 = this.@operator(ref cursor);
                    var opEnd = cursor;
                    var op = ValueOrDefault(r8);
                    if (r8 != null)
                    {
                        IParseResult<string> r9 = null;
                        r9 = this.EOF(ref cursor);
                        if (r9 != null)
                        {
                            r0 = this.ReturnHelper<string>(startCursor3, ref cursor, state =>
                                #line 250 "lucene-query.peg"
     
        op
                                #line default
                                );
                        }
                        else
                        {
                            cursor = startCursor3;
                        }
                    }
                    else
                    {
                        cursor = startCursor3;
                    }
                }
                else
                {
                    cursor = startCursor3;
                }
            }
            return r0;
        }

        private IParseResult<string> @operator(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "OR", ruleName: "operator");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "AND", ruleName: "operator");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "NOT", ruleName: "operator");
            }
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.ParseLiteral(ref cursor, "||");
                if (r1 != null)
                {
                    r0 = this.ReturnHelper<string>(startCursor0, ref cursor, state =>
                        #line 258 "lucene-query.peg"
           "OR"
                        #line default
                        , ruleName: "operator");
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor1 = cursor;
                IParseResult<string> r2 = null;
                r2 = this.ParseLiteral(ref cursor, "&&");
                if (r2 != null)
                {
                    r0 = this.ReturnHelper<string>(startCursor1, ref cursor, state =>
                        #line 259 "lucene-query.peg"
           "AND"
                        #line default
                        , ruleName: "operator");
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            return r0;
        }

        private IParseResult<string> prefix_operator_exp(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<IList<IList<string>>> r1 = null;
            var startCursor1 = cursor;
            var l0 = new List<IList<string>>();
            while (true)
            {
                IParseResult<IList<string>> r2 = null;
                r2 = this._(ref cursor);
                if (r2 != null)
                {
                    l0.Add(r2.Value);
                }
                else
                {
                    break;
                }
            }
            r1 = this.ReturnHelper<IList<IList<string>>>(startCursor1, ref cursor, state => l0.AsReadOnly());
            if (r1 != null)
            {
                IParseResult<string> r3 = null;
                var opStart = cursor;
                r3 = this.prefix_operator(ref cursor);
                var opEnd = cursor;
                var op = ValueOrDefault(r3);
                if (r3 != null)
                {
                    r0 = this.ReturnHelper<string>(startCursor0, ref cursor, state =>
                        #line 263 "lucene-query.peg"
     
        op
                        #line default
                        );
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> prefix_operator(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "+", ruleName: "prefix_operator");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "-", ruleName: "prefix_operator");
            }
            return r0;
        }

        private IParseResult<IList<string>> _(ref Cursor cursor)
        {
            IParseResult<IList<string>> r0 = null;
            var startCursor0 = cursor;
            var l0 = new List<string>();
            while (true)
            {
                IParseResult<string> r1 = null;
                r1 = this.ParseClass(ref cursor, "  \t\t\r\r\n\n\f\f");
                if (r1 != null)
                {
                    l0.Add(r1.Value);
                }
                else
                {
                    break;
                }
            }
            if (l0.Count >= 1)
            {
                r0 = this.ReturnHelper<IList<string>>(startCursor0, ref cursor, state => l0.AsReadOnly());
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> EOF(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParseAny(ref cursor);
            if (r1 == null)
            {
                r0 = this.ReturnHelper<string>(cursor, ref cursor, state => string.Empty);
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> ParseLiteral(ref Cursor cursor, string literal, bool ignoreCase = false, string ruleName = null)
        {
            if (cursor.Location + literal.Length <= cursor.Subject.Length)
            {
                var substr = cursor.Subject.Substring(cursor.Location, literal.Length);
                if (ignoreCase ? substr.Equals(literal, StringComparison.OrdinalIgnoreCase) : substr == literal)
                {
                    var endCursor = cursor.Advance(substr.Length);
                    var result = this.ReturnHelper<string>(cursor, ref endCursor, state => substr, ruleName);
                    cursor = endCursor;
                    return result;
                }
            }
            return null;
        }

        private IParseResult<string> ParseClass(ref Cursor cursor, string characterRanges, bool negated = false, bool ignoreCase = false, string ruleName = null)
        {
            if (cursor.Location + 1 <= cursor.Subject.Length)
            {
                var c = cursor.Subject[cursor.Location];
                bool match = false;
                for (int i = 0; !match && i < characterRanges.Length; i += 2)
                {
                    match = c >= characterRanges[i] && c <= characterRanges[i + 1];
                }
                if (!match && ignoreCase && (char.IsUpper(c) || char.IsLower(c)))
                {
                    var cs = c.ToString();
                    for (int i = 0; !match && i < characterRanges.Length; i += 2)
                    {
                        var min = characterRanges[i];
                        var max = characterRanges[i + 1];
                        for (char o = min; !match && o <= max; o++)
                        {
                            match = (char.IsUpper(o) || char.IsLower(o)) && cs.Equals(o.ToString(), StringComparison.CurrentCultureIgnoreCase);
                        }
                    }
                }
                if (match ^ negated)
                {
                    var endCursor = cursor.Advance(1);
                    var substr = cursor.Subject.Substring(cursor.Location, 1);
                    var result = this.ReturnHelper<string>(cursor, ref endCursor, state => substr, ruleName);
                    cursor = endCursor;
                    return result;
                }
            }
            return null;
        }

        private IParseResult<string> ParseAny(ref Cursor cursor, string ruleName = null)
        {
            if (cursor.Location + 1 <= cursor.Subject.Length)
            {
                var substr = cursor.Subject.Substring(cursor.Location, 1);
                var endCursor = cursor.Advance(1);
                var result = this.ReturnHelper<string>(cursor, ref endCursor, state => substr, ruleName);
                cursor = endCursor;
                return result;
            }
            return null;
        }

        private IParseResult<T> ReturnHelper<T>(Cursor startCursor, ref Cursor endCursor, Func<Cursor, T> wrappedCode, string ruleName = null)
        {
            if (ruleName != null)
            {
                var state = endCursor.WithMutability(true);
                var element = new LexicalElement { StartCursor = startCursor, EndCursor = endCursor, Name = ruleName };
                state["_lexical"] = (state["_lexical"] as ListNode<LexicalElement>).Push(element);
                element.EndCursor = endCursor = state.WithMutability(false);
            }
            var result = wrappedCode(endCursor);
            var lexical = result as ILexical;
            if (lexical != null && lexical.StartCursor == null && lexical.EndCursor == null)
            {
                lexical.StartCursor = startCursor;
                lexical.EndCursor = endCursor;
            }
            return new ParseResult<T>(startCursor, endCursor, result);
        }

        private Exception ExceptionHelper(Cursor cursor, Func<Cursor, string> wrappedCode)
        {
            var ex = new FormatException(wrappedCode(cursor));
            ex.Data["cursor"] = cursor;
            return ex;
        }

        private T ValueOrDefault<T>(IParseResult<T> result)
        {
            return result == null
                ? default(T)
                : result.Value;
        }
    }
}
